{% set name = "gis-utils" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1d3ffc7e388f1f72b518fc1eb4c54f11122e1884686225dc2ba9e98f680f1a91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=61
    - pip
  run:
    - python >=3.6
    - matplotlib-base
    - numpy
    - scipy
    - pandas
    - geopandas
    - xarray
    - fiona
    - shapely
    - pyproj
    - rasterio


test:
  imports:
    - gisutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aleaf/gisutils
  summary: Convenience functions for working with geospatial data in python.
  license: BSD-3-Clause-Modification
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aleaf
    - jdhughes-usgs
