{% set name = "gis-utils" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6ee352e40214fe666624cb902a33aa106cf63f83a24c13c9ea839d5f01c4626e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - scipy
    - pandas
    - geopandas
    - xarray
    - fiona
    - shapely
    - pyproj
    - rasterio


test:
  imports:
    - gisutils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aleaf/gisutils
  summary: Convenience functions for working with geospatial data in python.
  license: BSD-3-Clause-Modification
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aleaf
    - jdhughes-dev
